### PR TITLE
Fixed file descriptor leaks.

### PR DESCRIPTION
**Pull request by derrickburns**
This fixes two file descriptor leaks that affect clients, including `hydrophone`.

### CODE REVIEW

**Comment by derrickburns** [comment]
I have not run hydrophone with this change. So I don't know if this fixes all the leaks. However, this change does address all the leaks of this pattern.

Derrick

**Comment by darinkrauss** [comment]
We historically run and test all changes in our local environment before requesting review and, after approval, sending to QA.

**Comment by derrickburns** [comment]
[Fix Hydrophone open file leak](https://trello.com/c/vdgvI6Uz/627-fix-hydrophone-open-file-leak)

**Comment by derrickburns** [comment]
@pazaan Are you ok with these changes?

**Comment by derrickburns** [comment]
[Fix Shoreline open file leak](https://trello.com/c/j16txRTz/635-fix-shoreline-open-file-leak)

**Pull request merged**
