### PR TITLE
Various changes for custodial users

### PR DESCRIPTION
**Pull request by darinkrauss**
Look at each commit for what specifically was done.

@jh-bate

### CODE REVIEW

**Comment by darinkrauss** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fROzd9mX&#x2F;12-platform-clinic-0-ux-5-dev-2-tst-platform-supports-true-child-accounts"> [platform][clinic] &lt;0:ux 5:dev, 2:tst&gt; Platform supports true child accounts</a>

**Comment by jh-bate** [comment]
LGTM as discussed

**Comment by jh-bate** [comment]
lgtm @darinkrauss

**Comment by darinkrauss** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TIEJfsUg&#x2F;5-platform-uploader-clinic-mode-0-ux-3-dev-2-test-enable-clinic-mode-for-the-uploader"> [platform][uploader] [clinic-mode] &lt;0:ux 3:dev 2:test&gt; Enable clinic-mode for the uploader</a>

**Comment by darinkrauss** [comment]
@jh-bate Ping. See latest commit for adding new error code to Status response.

**Pull request merged**
